### ISSUE TITLE
handling two events that transition to and from same state

### ISSUE THREAD

**Issue by clindh** [rolfvreijdenberger/izzum-statemachine#8] opened 2016-06-30 14:05 UTC
I have a state that I want to be able to handle two different events, that transit to the same state (but with different commands on the transition) - but that does not seem to be possible? As these two transitions get the same name (fromState_to_toState) - the second is never added. 

Could a simple solution be to be able to set a custom name on the transition, overriding the generated default name?

**Comment by rolfvreijdenberger** [comment] 2016-06-30 14:19
Hi, 

In my opinion you would not want to do that.

it seems you should do that by defining multiple target states. a transition from A to B should execute the same piece of logic every time and not depending on what the triggering event is (basically you would be introducing conditional logic in 1 transition)

what you would want to do would be to introduce a state C.
define 
A->B (event: 'ab') logic 1
A->C(event: 'ac') logic 2
C->B('cb') always allow transition from b (and optionally extra logic)

so you would either take the path AB or ACB, thus going from A and ending up in B or going from A to C and ending up in B.

does that make sense for your use case?

**Comment by rolfvreijdenberger** [comment] 2016-06-30 14:25
to explain further. there is always one transition from state A to B. not multiple as you found out. This is by design. we are changing a state and are executing the same piece of logic  for that transition every time (if the state change is allowed)

**Comment by rolfvreijdenberger** [comment] 2016-06-30 14:31
and one further explanation: one of the 'design patterns' for the statemachines we use at my ISP is exactly the one described above, it is a triangular form which represents a conditional path in the statemachine graph ('conditional flow). 
here are some
● linear flow: one way out, mostly used for bookkeeping state
● conditional flow: triangular flow representing a choice route
● funnel state: a state that functions as an entry to a final state with
potentially many states pointing to it. the state has no logic
associated with that flow but functions as a bookkeeping state
two ways out: don't overcomplicate by only using two outgoing
transitions
● self transition: transition to self
● polling state: state that has a rule that polls a third party service
●
active state: a state named after the activity it will perform (activity on
entry/exit)
● passive state: a state that performs no activity (activity on transition)
● bookkeeping state: does nothing, only records that is has been there

if you define two events anyway, then it makes more sense to just go to different states

**Comment by rolfvreijdenberger** [comment] 2016-06-30 14:35
see this presentation I gave at a phpmeetup for more core concepts explained
[2015_09_17_amsterdamphpmeetup.pdf](https://github.com/rolfvreijdenberger/izzum-statemachine/files/341665/2015_09_17_amsterdamphpmeetup.pdf)

**Comment by clindh** [comment] 2016-06-30 15:14
Thanks Rolf for the help and detailed description, lots to learn here!  I guess I am centering to much on "what different events can occur, and what should happen then".

So besides the different commands I wanted (lets skip that), it would not be good design to have two events trigger the same transition either?   For example an engine with events "startEngingeEngaged" and "handcrankTurned" both puts it in state "Engine is running"? (maybe a bad example...)   It would be better/necessary to transition to two "bookkeeping" states ("Started by crank" and "Started by engine"), both transitioning on to "Engine is running"?

**Comment by rolfvreijdenberger** [comment] 2016-07-10 19:14
Hi @clindh  I'm closing this issue. hope you found a good solution in your implementation!

**Closed by rolfvreijdenberger** 2016-07-10 19:14 UTC
Labels: question
